- name: Configure App2 with Nginx 
  hosts: "{{ public_ip }}"
  gather_facts: true
  become: yes

  tasks:
  # SELinux
  - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
    seboolean:
      name: httpd_can_network_connect
      state: yes
      persistent: yes

  - name: Allow Nginx to listen on tcp port 8080
    seport:
      ports: 8080
      proto: tcp
      setype: http_port_t
      state: present

  # Nginx 
  - name: install the latest version of Nginx
    yum:
      name: nginx
      state: latest
  
  - name: Final nginx config Template to /etc/nginx/nginx.conf
    template:
      src: app2-nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: '0644'

  - name: Copy the index.html 
    copy:
      src: index-app2.html
      dest: /usr/share/nginx/html/index.html
      owner: nginx
      group: nginx
      mode: '0644'

  - name: enable service nginx and ensure it is not masked
    systemd:
      name: nginx
      enabled: yes
      masked: no

  - name: reload service nginx, in all cases
    systemd:
      name: nginx
      state: reloaded

  - name: Make sure a nginx is running
    systemd:
      state: started
      name: nginx

  - name: Test HTTP connection 
    uri:
      url: "http://localhost:8080/"
      status_code: 200
    #delegate_to: localhost
    #become: false
    retries: 12 # 12 * 5 seconds = 1 min
    delay: 5 # Every 5 seconds

